name: Daily Wallpaper Update

on:
  schedule:
    # 北京时间每天 08:00 → UTC 00:00
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-wallpaper:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install playwright beautifulsoup4 html5lib
          playwright install --with-deps

      - name: Run update script
        run: |
          python main.py

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add wallpaper.json
          git diff --quiet || git commit -m "更新壁纸信息"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
